__rethrow_casa_exceptions = True
h_init()
try:
    hif_restoredata (vis=['uid___A002_X9998b8_Xee3', 'uid___A002_X9998b8_X11eb', 'uid___A002_X9a3e71_Xffc', 'uid___A002_X9a3e71_X1256', 'uid___A002_X9a3e71_X15ca', 'uid___A002_X9a3e71_X1839', 'uid___A002_X9aca45_Xf3f'], session=['session_1', 'session_1', 'session_1', 'session_1', 'session_1', 'session_1', 'session_1'])
finally:
    h_save()
